'use strict';
// One continuing campaign through actual worker_threads and the shipped SDK.
// The Worker bridge and engine are extracted from the target HTML, never a loose
// implementation file. Test-only fixture hooks run between stopped SDK sessions.
// No browser, GPU, visual quality, storage quota, or device-FPS claim is made.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto'),{Worker}=require('worker_threads');
const file=process.argv[2]||`${__dirname}/../index.html`;
const output=process.env.BLOOM_SAVE_REPORT||`${__dirname}/v63-save-e2e-results.json`;
const html=fs.readFileSync(file,'utf8');
const makeSession=require('./main-harness.cjs').session;
const allWorkers=[];function session(){const s=makeSession(file,html);allWorkers.push(s);return s}
const exact='BloomOwnedSDK.hashBytes(bloomAdapter.save())';
const normalizedBytes='(()=>{const c=BloomLiveCodec.decode(bloomAdapter.save());c.tick=0;return BloomLiveCodec.encode(c)})()';
const report={status:'RUNNING',file,sha256:crypto.createHash('sha256').update(html).digest('hex'),scope:'One continuing campaign; isolated native V8 realms running the actual main-thread runtime, engine and pinned embedded SDK extracted from target HTML. Declared stopped-session earned inventory/XP, durable encounter and damage fixtures. Disk-loaded branch equivalence normalizes only the SDK tick. No browser/GPU/storage-quota/device-performance claim.',checks:[],chapters:[]};
function check(name,ok,data){if(!ok&&data!==undefined)console.error('FAILED DATA',JSON.stringify(data));assert(ok,name);report.checks.push(name);if(data)report.chapters.push({name,...data});console.log('PASS',name)}
async function same(a,b,label){const [aa,bb]=await Promise.all([a.read(normalizedBytes),b.read(normalizedBytes)]),x=Buffer.from(aa),y=Buffer.from(bb),equal=x.equals(y);if(!equal){fs.writeFileSync('/tmp/v63-save-continuous.bin',x);fs.writeFileSync('/tmp/v63-save-loaded.bin',y)}check(label,equal,{normalizedSha256:crypto.createHash('sha256').update(x).digest('hex'),comparedBytes:x.length});}
function diskLive(disk){const d=typeof disk==='string'?JSON.parse(disk):disk;if(Array.isArray(d.live))return Uint8Array.from(d.live);assert.equal(d.schema,'bloom-snapshot-disk-v3');const value=typeof d.live==='string'?d.live:d.live?.data??d.payload??d.data;assert.equal(typeof value,'string','v3 embeds base64 live payload');return Uint8Array.from(Buffer.from(value,'base64'));}
async function fork(a,label){const disk=await a.request('snapshot'),b=session(),before=await a.read('({tick:bloomTick,time:state.time})');const loaded=await b.init(disk);check(label+' imports successfully',loaded.loaded&&!loaded.persistenceProtected);const after=await b.read('({tick:bloomTick,time:state.time})');check(label+' resets SDK tick only',after.tick===0&&after.time===before.time,{sourceTick:before.tick,loadedTick:after.tick,time:after.time});await same(a,b,label+' preserves complete canonical graph');return{b,disk};}
async function continueTogether(a,b,count,label){a.control();b.control();for(let i=0;i<count;i++){const input={x:i%11<5?.35:0,y:i%13<4?.25:0,manual:true};a.control({input});b.control({input});await Promise.all([a.tick(),b.tick()]);if(i===0||i===count-1||i%9===0)await same(a,b,`${label}, future tick ${i+1}`)}}
(async()=>{
 const compatibility=JSON.parse(fs.readFileSync(`${__dirname}/fixtures/v63-compatibility.json`,'utf8')),old=session();
 check('Original published v63 save imports without progress wipe',(await old.init(compatibility.disk)).loaded);
 const canonicalSHA=async()=>crypto.createHash('sha256').update(Buffer.from(await old.read('bloomAdapter.save()'))).digest('hex');
 check('Original v63 save restores byte-identical canonical authority',await canonicalSHA()===compatibility.initialSHA256);
 old.control({input:{x:.35,y:.25,manual:true}});await old.tick(6);
 check('Gamekit SDK preserves exact future evolution of original v63 save',await canonicalSHA()===compatibility.futureSHA256);await old.close();
 const a=session();await a.init();a.control({input:{x:.5,y:0,manual:true}});const startX=await a.read('state.mother.x');await a.tick(3);check('Main-thread SDK advances real movement before checkpoint',(await a.read('state.mother.x'))>startX);
 await a.fixture(`
  for(const c of state.camps){c.enabled=false;c.spawned=true;c.regrowth=[]}
  for(const u of state.units)if(u.team==='enemy'){u.stun=1e6;u.aggroAt=u.wanderAt=state.time+1e6}
  const m=state.mother,q=ThemedTerrain.safePoint(1800,1800,moaBodyRadius(m));m.x=m.worldX=q.x;m.y=m.worldY=q.y;resetMoaBody(m);spatialUnit(m,true);
  Object.assign(abilityState(),{ranks:{pod:1,lob:1,thorn:1,spore:1,beam:1,chain:1,breath:1},mods:{},chosen:7,level:9,xp:abilityThreshold(9),draft:null});moaSyncLevelHP(m);m.hp=m.maxHp;
  rarityAcquire(-1,'swordsman',0,3);for(const r of rarityAccount(-1).active.slice(0,2)){rarityPlayerLock(r.uid,true);die(rarityBody(r),null)}
  const pos=ThemedTerrain.safePoint(m.x+130,m.y,20),t=spawn('shellbug','enemy',pos.x,pos.y,{camp:0,rarityGrade:1});t.hp=t.maxHp=1e7;t.stun=1e6;t.aggroAt=t.wanderAt=state.time+1e6;state.camps[0].remaining++;globalThis.qaTarget=t.id;
  state.rng=100000;state.mother.auxCooldowns={};clearPointNav();
 `);
 const view=await a.read('visibleHuntFromViewport(690,950)');await a.command(view);await a.command({type:'auto',enabled:false});a.control();await a.tick();
 const combat=await a.read('({shots:projectiles.map(p=>({weapon:p.weapon,shotId:p.shotId,ageMs:p.ageMs})),channels:state.mother.gearChannels,hp:idMap.get(qaTarget).hp,terrain:state.campaign.themedTerrain,view:state.campaign.huntView,owned:rarityOwnedCount(-1),dead:rarityAccount(-1).active.filter(r=>r.body).length,deadRecords:rarityAccount(-1).active.filter(r=>r.body).map(r=>({uid:r.uid,id:r.entityId}))})');
 check('Continuing earned checkpoint has real active beam/breath and dead owned bodies',combat.shots.some(p=>p.weapon==='beam')&&combat.shots.some(p=>p.weapon==='breath')&&combat.dead===2&&combat.owned===3,combat);
 check('Production huntView command commits non-default viewport',combat.view.halfWidth===view.halfWidth&&combat.view.halfHeight===view.halfHeight,{huntView:combat.view});
 a.control({paused:true,modalKind:'pause'});const pausedBefore=await a.read(exact),pausedTime=await a.read('state.time'),disk=await a.request('snapshot'),envelope=JSON.parse(disk);
 check('New disk uses compact v3 base64 envelope',envelope.schema==='bloom-snapshot-disk-v3'&&!Array.isArray(envelope.live),{diskBytes:Buffer.byteLength(disk),liveBytes:diskLive(disk).length,metadata:Object.fromEntries(Object.entries(envelope).filter(([k])=>!['live','payload','data'].includes(k)))});
 check('Save while paused is authority-read-only',await a.request('save')&&await a.read(exact)===pausedBefore&&await a.read('state.time')===pausedTime);
 const canonical=await a.read('({bytes:bloomAdapter.save(),tick:bloomTick,tickRate:CONFIG.sim.tickRate,time:state.time})');
 check('Disk payload is exactly the existing canonical SDK snapshot',Buffer.from(diskLive(disk)).equals(Buffer.from(canonical.bytes)));
 check('Version/codec/clock/length/checksum metadata matches authoritative bytes',envelope.formatVersion===3&&envelope.simulationVersion==='bloom-webgl-live-ms-v2'&&envelope.codec==='bloom-live-graph-v3'&&envelope.encoding==='base64'&&envelope.tick===canonical.tick&&envelope.tickRate===canonical.tickRate&&envelope.worldTime===canonical.time&&envelope.byteLength===canonical.bytes.length&&envelope.checksum.algorithm==='fnv1a32'&&envelope.checksum.value===pausedBefore);
 const firstCached=await a.request('snapshot'),cacheBefore=await a.read('bloomSnapshotStore.metrics()'),secondCached=await a.request('snapshot'),cacheAfter=await a.read('bloomSnapshotStore.metrics()');
 check('Repeated paused snapshot reuses exact disk string without recapture or re-encoding',firstCached===secondCached&&cacheAfter.captures===cacheBefore.captures&&cacheAfter.diskEncodes===cacheBefore.diskEncodes,{before:cacheBefore,after:cacheAfter});
 const returned=await a.read('(()=>{const bytes=bloomAdapter.save(),hash=BloomOwnedSDK.hashBytes(bytes);bytes[10]^=255;return {hash,mutatedHash:BloomOwnedSDK.hashBytes(bytes)}})()'),aliasDisk=await a.request('snapshot');
 check('Mutating returned adapter bytes cannot poison private disk cache',returned.hash!==returned.mutatedHash&&JSON.parse(aliasDisk).checksum.value===returned.hash&&Buffer.from(diskLive(aliasDisk)).equals(Buffer.from(canonical.bytes)));
 
 const branch1=await fork(a,'Active-channel paused checkpoint');await continueTogether(a,branch1.b,18,'Active channels and terrain');
 check('Loaded attacks deliver future real damage',(await a.read('idMap.get(qaTarget).hp'))<combat.hp);await branch1.b.close();
 // The same campaign actually climbs a nonzero terrain ramp before disk forking.
 await a.fixture('const crest=ThemedTerrain.ridges[0].points[11],m=state.mother,q=ThemedTerrain.safePoint(crest.x,crest.y+180,moaBodyRadius(m));clearPointNav();autoHunt.enabled=false;m.x=m.worldX=q.x;m.y=m.worldY=q.y;resetMoaBody(m);spatialUnit(m,true);rarityRecall(-1);');
 a.control({input:{x:0,y:-1,manual:true}});await a.tick(3);const uphill=await a.read('({x:state.mother.x,y:state.mother.y,z:state.mother.z,groundZ:state.mother.groundZ})');check('Terrain checkpoint has actual elevated support and body height',uphill.groundZ>15&&Math.abs(uphill.z-uphill.groundZ)<.001,uphill);
 const terrainBranch=await fork(a,'Elevated terrain checkpoint');for(let i=0;i<5;i++){for(const w of [a,terrainBranch.b])w.control({input:{x:0,y:-1,manual:true}});await Promise.all([a.tick(),terrainBranch.b.tick()]);await same(a,terrainBranch.b,'Actual terrain climb after disk, tick '+(i+1))}check('Both branches continue real uphill motion',(await a.read('state.mother.groundZ'))>uphill.groundZ);await terrainBranch.b.close();
 // Earn one pending choice, then obtain its actual materialized draft through the SDK.
 await a.fixture("rarityAcquire(-1,'swordsman',0,12);const s=abilityState();s.level=Math.max(s.level,s.chosen+2);s.xp=abilityThreshold(s.level);s.draft=null;moaSyncLevelHP(state.mother);state.mother.hp=state.mother.maxHp;");
 a.control({paused:true,modalKind:'ability'});await a.command({type:'abilityDraft'});await a.tick();const draft=await a.read('structuredClone(abilityState().draft)');check('Real SDK abilityDraft materializes a three-card offer',draft?.ids.length===3&&draft.offers.length===3);
 const branch2=await fork(a,'Pending materialized card checkpoint');check('Materialized draft and RNG survive disk',JSON.stringify(await a.read('({draft:abilityState().draft,rng:abilityState().rng})'))===JSON.stringify(await branch2.b.read('({draft:abilityState().draft,rng:abilityState().rng})')));
 const preFusionRNG=await a.read('state.rng');const choice=await a.read('({type:"abilityChoice",cardId:abilityState().draft.ids[0],offer:abilityState().chosen})');for(const w of [a,branch2.b]){w.control({paused:true,modalKind:'ability'});await w.command(choice);await w.command({type:'rarityFuse',unitType:'swordsman',grade:0,max:true});await w.tick()}
 await same(a,branch2.b,'Identical future card and RNG fusion commands');const fusion=await a.read('structuredClone(rarityAccount(-1).lastFusion)');check('Fusion genuinely consumes earned inventory and advances RNG',fusion?.attempts>0&&fusion.consumed>0&&await a.read('state.rng')!==preFusionRNG,{fusion,previousRNG:preFusionRNG,currentRNG:await a.read('state.rng')});await continueTogether(a,branch2.b,12,'Post-choice/fusion');await branch2.b.close();
 // Save is issued immediately after a command, with no intervening manual tick.
 a.control({paused:true,modalKind:'pause'});const beforePending=await a.read('({tick:bloomTick,time:state.time,enabled:autoHunt.enabled})');await a.command({type:'auto',enabled:!beforePending.enabled});const pendingDisk=await a.request('snapshot');
 const afterPending=await a.read('({tick:bloomTick,time:state.time,enabled:autoHunt.enabled,pending:bloomInputPending})');check('Immediate snapshot settles queued command at a suspended SDK boundary',afterPending.enabled===!beforePending.enabled&&afterPending.pending===0&&afterPending.time===beforePending.time,{before:beforePending,after:afterPending});const pendingBranch=session();await pendingBranch.init(pendingDisk);await same(a,pendingBranch,'Saved queued command is present exactly once');await continueTogether(a,pendingBranch,4,'After pending-command save');await pendingBranch.close();
 // A running save/export may observe the next scheduled SDK tick, never create
 // an extra early combat tick. The following read is a FIFO Worker barrier.
 a.control();const runningBefore=await a.read('({tick:bloomTick,time:state.time,view:structuredClone(state.campaign.huntView)})'),runningView={type:'huntView',halfWidth:runningBefore.view.halfWidth+8,halfHeight:runningBefore.view.halfHeight,insetX:runningBefore.view.insetX,insetY:runningBefore.view.insetY,huntInset:runningBefore.view.huntInset};
 await a.command(runningView);let runningSaveSettled=false,runningExportSettled=false;const runningDiskCount=a.messages.filter(m=>m.type==='disk').length;
 const runningSave=a.request('save').then(value=>{runningSaveSettled=true;return{value}},error=>{runningSaveSettled=true;return{error:error.message}}),runningExport=a.request('snapshot').then(value=>{runningExportSettled=true;return{value}},error=>{runningExportSettled=true;return{error:error.message}});
 const runningWaiting=await a.read('({tick:bloomTick,time:state.time,pending:bloomInputPending,halfWidth:state.campaign.huntView.halfWidth})');
 check('Running pending save and export wait without an early SDK/combat tick',!runningSaveSettled&&!runningExportSettled&&runningWaiting.tick===runningBefore.tick&&runningWaiting.time===runningBefore.time&&runningWaiting.pending>0&&runningWaiting.halfWidth===runningBefore.view.halfWidth&&a.messages.filter(m=>m.type==='disk').length===runningDiskCount,{before:runningBefore,waiting:runningWaiting});
 await a.tick();const [runningSaved,runningExported]=await Promise.all([runningSave,runningExport]),runningAfter=await a.read('({tick:bloomTick,time:state.time,pending:bloomInputPending,halfWidth:state.campaign.huntView.halfWidth})'),runningEnvelope=runningExported.value&&JSON.parse(runningExported.value);
 check('Existing next SDK advance commits command and resolves both queued saves at that tick',runningSaved.value===true&&!runningExported.error&&runningAfter.tick===runningBefore.tick+1&&Math.abs(runningAfter.time-runningBefore.time-.1)<1e-8&&runningAfter.pending===0&&runningAfter.halfWidth===runningView.halfWidth&&runningEnvelope.tick===runningAfter.tick&&runningEnvelope.worldTime===runningAfter.time&&a.messages.filter(m=>m.type==='disk').at(-1).tick===runningAfter.tick,{after:runningAfter,savedTick:runningEnvelope?.tick});
 // A valid load supersedes earlier unresolved save requests; no stale request
 // may silently save the replacement world or consume an old queued command.
 const boundaryWorker=session();await boundaryWorker.init(runningExported.value);boundaryWorker.control();await boundaryWorker.command({...runningView,halfWidth:runningView.halfWidth+8});let boundarySaveSettled=false,boundaryExportSettled=false;
 const boundarySave=boundaryWorker.request('save').then(value=>{boundarySaveSettled=true;return{value}},error=>{boundarySaveSettled=true;return{error:error.message}}),boundaryExport=boundaryWorker.request('snapshot').then(value=>{boundaryExportSettled=true;return{value}},error=>{boundaryExportSettled=true;return{error:error.message}});
 const boundaryWaiting=await boundaryWorker.read('({tick:bloomTick,time:state.time,pending:bloomInputPending})');check('Session-boundary test has genuinely queued unresolved requests',!boundarySaveSettled&&!boundaryExportSettled&&boundaryWaiting.tick===0&&boundaryWaiting.pending>0);
 const boundaryDiskCount=boundaryWorker.messages.filter(m=>m.type==='disk').length;check('Replacement load succeeds while older saves await next tick',await boundaryWorker.request('load',{disk:runningExported.value}));const boundaryResults=await Promise.all([boundarySave,boundaryExport]);
 check('Session boundary cancels ordinary save and explicitly rejects superseded export',boundaryResults[0].value===false&&!boundaryResults[0].error&&/Save superseded by session boundary/.test(boundaryResults[1].error||'')&&boundaryWorker.messages.filter(m=>m.type==='disk').length===boundaryDiskCount+1&&await boundaryWorker.read('bloomInputPending')===0,{results:boundaryResults,newDiskPublications:boundaryWorker.messages.filter(m=>m.type==='disk').length-boundaryDiskCount});await same(a,boundaryWorker,'Boundary cancellation preserves the intended replacement snapshot');await boundaryWorker.close();
 // An actually defeated campaign is saved, imported, and recovered by commands.
 report.chapters.push({name:'New encounter after north-ridge travel',priorCenterTargetStillPresent:await a.read('idMap.has(qaTarget)'),fixture:'The earlier center-floor target may naturally leave the active spawn ring after ridge travel. Create a new local full-identity durable encounter, relaunch both channels, then apply production lethal damage.'});
 await a.fixture('const m=state.mother,q=ThemedTerrain.safePoint(1800,1800,moaBodyRadius(m));m.x=m.worldX=q.x;m.y=m.worldY=q.y;resetMoaBody(m);spatialUnit(m,true);rarityRecall(-1);for(let i=projectiles.length-1;i>=0;i--)discardProjectile(i);m.auxCooldowns={};clearPointNav();autoHunt.enabled=false;const p=ThemedTerrain.safePoint(m.x+110,m.y,20),t=spawn("shellbug","enemy",p.x,p.y,{camp:0,rarityGrade:1});t.hp=t.maxHp=1e7;t.stun=1e6;t.aggroAt=t.wanderAt=state.time+1e6;state.camps[0].remaining++;globalThis.qaTarget=t.id;');
 a.control();await a.tick();check('Defeat fixture begins with live local attacker and active channels',await a.read('!!idMap.get(qaTarget)&&gearChannelActive(state.mother,"breath")&&gearChannelActive(state.mother,"beam")'));
 await a.fixture('bloomInTick=true;try{damage(idMap.get(qaTarget),state.mother,1e9,"melee")}finally{bloomInTick=false}');check('Production lethal damage creates saved dead state and clears channels',await a.read('state.dead&&projectiles.length===0&&!gearChannelActive(state.mother,"breath")&&!gearChannelActive(state.mother,"beam")'));
 const branch3=await fork(a,'Dead campaign checkpoint');for(const w of [a,branch3.b]){w.control({paused:true,modalKind:'defeat'});await w.command({type:'recover'});await w.tick()}await same(a,branch3.b,'Recovery command restores same authority');check('Recovery revives the same upgraded Moa',await a.read('!state.dead&&abilityState().chosen>=8'));
 const recoveryShotSerial=await a.read('abilityShotSerial');await continueTogether(a,branch3.b,60,'Recovery and repeated channel lifecycle');
 check('Recovered weapon channels genuinely recast without orphan latches',await a.read('abilityShotSerial')>recoveryShotSerial+7&&await a.read('["beam","breath"].every(id=>!gearChannelActive(state.mother,id)||projectiles.some(p=>p.weapon===id&&!p.finished))'),{beforeSerial:recoveryShotSerial,afterSerial:await a.read('abilityShotSerial')});
 for(const r of combat.deadRecords)check('Saved locked recruit revives with stable permanent identity '+r.uid,await a.read(`(()=>{const r=rarityRecord(${r.uid})?.record;return !!r&&!r.body&&r.entityId===${r.id}&&rarityBody(r)?.hp>0&&r.locked})()`));await branch3.b.close();
 // Invalid imports must not mutate identity, tick, session, or queued commands.
 a.control({paused:true,modalKind:'pause'});const valid=await a.request('snapshot');const legacy=JSON.stringify({schema:'bloom-webgl-disk-ms-v2',live:Array.from(diskLive(valid))});const legacyBranch=session();check('Strict legacy number-array envelope is still readable',(await legacyBranch.init(legacy)).loaded);await same(a,legacyBranch,'Legacy import preserves canonical world');await legacyBranch.close();
 const corrupt=JSON.parse(valid);if(typeof corrupt.live==='string')corrupt.live=(corrupt.live[0]==='A'?'B':'A')+corrupt.live.slice(1);else if(corrupt.live?.data)corrupt.live.data=(corrupt.live.data[0]==='A'?'B':'A')+corrupt.live.data.slice(1);else throw Error('Update checksum-corruption test for actual v3 payload key');
 const wrongTick=JSON.parse(valid);wrongTick.tick++;const wrongLength=JSON.parse(valid);wrongLength.byteLength++;const wrongChecksum=JSON.parse(valid);wrongChecksum.checksum.value^=1;
 const invalids=['{invalid save}',JSON.stringify({schema:'unknown',live:[]}),JSON.stringify(corrupt),JSON.stringify({schema:'bloom-webgl-disk-ms-v2',live:[256,0,0]}),JSON.stringify(wrongTick),JSON.stringify(wrongLength),JSON.stringify(wrongChecksum),JSON.stringify({schema:'bloom-webgl-disk-ms-v2',live:[0,1.5,2]})];
 for(const [i,bad]of invalids.entries()){await a.read('globalThis.qaIdentity=state;globalThis.qaSession=bloomSession;true');const hash=await a.read(exact),status=await a.request('inspect'),disks=a.messages.filter(m=>m.type==='disk').length;check(`Invalid import ${i+1} is rejected`,await a.request('load',{disk:bad})===false);const after=await a.request('inspect');check(`Invalid import ${i+1} is nonmutating and does not overwrite persistence`,await a.read(exact)===hash&&await a.read('state===qaIdentity&&bloomSession===qaSession')&&status.tick===after.tick&&status.epoch===after.epoch&&a.messages.filter(m=>m.type==='disk').length===disks)}
 const queuedBefore=await a.read('({enabled:autoHunt.enabled,tick:bloomTick,time:state.time})');await a.command({type:'auto',enabled:!queuedBefore.enabled});const pendingBefore=await a.read('bloomInputPending'),pendingHash=await a.read(exact);check('Malformed import with queued command is rejected',await a.request('load',{disk:JSON.stringify(wrongTick)})===false);check('Rejected import preserves pending command and live tick',await a.read('bloomInputPending')===pendingBefore&&await a.read(exact)===pendingHash);await a.request('snapshot');check('Preserved pending command executes exactly once on next save',await a.read('bloomInputPending')===0&&await a.read('autoHunt.enabled')===!queuedBefore.enabled&&await a.read('bloomTick')===queuedBefore.tick+1&&await a.read('state.time')===queuedBefore.time);
 // Continue the same world in two native-realm engines exchanging real SDK wire packets.
 const {engine,pair}=require('./native-engine.cjs'),e=engine(file,html);e.run('BloomSimulation.initialize(12345);BloomSimulation.createSession();playing=true;paused=false;modalKind=""');e.c.disk=await a.request('snapshot');check('Final main-thread world enters same shipped native SDK branch',e.run('BloomSimulation.disk.load(disk)'));
 const sdkNames=e.run('Object.keys(BloomOwnedSDK).sort().join(",")');
 check('Gamekit compatibility SDK exposes complete session/codec/loop/replay API', ['createSession','createLoop','playReplay','binaryCodec','SeededPRNG','hashBytes'].every(name=>sdkNames.split(',').includes(name)));
 const pure=Buffer.from(e.run('BloomSimulation.adapter.save()'));e.c.pure=Uint8Array.from(pure);e.run('BloomSimulation.adapter.load(pure)');check('Pure rollback adapter restores byte-identical live snapshot',pure.equals(Buffer.from(e.run('BloomSimulation.adapter.save()'))));
 const net=pair(e);for(let i=0;i<6;i++)net.advance();net.delay();e.run('setAutoHunt(!autoHunt.enabled)');for(let i=0;i<6;i++)net.advance({x:0,y:.6,manual:true});check('Delayed real SDK input produces prediction divergence',!net.same());net.release();for(let i=0;i<6;i++)net.advance();const metrics=net.peer.json('BloomSimulation.session.metrics');check('Real SDK late-packet rollback still converges exactly',net.same()&&metrics.rollbacks>=1&&metrics.resimulatedTicks>=6&&metrics.rejectedPackets===0&&metrics.hashMismatches===0,{metrics});e.run('BloomSimulation.session.close()');net.peer.run('BloomSimulation.session.close()');
 const rejected=session(),startup=await rejected.init('{invalid saved file}');check('Invalid startup disk remains persistence-protected',startup.persistenceProtected&&await rejected.request('save')===false);await rejected.request('reset');check('Explicit reset clears startup persistence protection',await rejected.request('save')===true);const fatalDisk=await rejected.request('snapshot');await rejected.request('__breakSession');const diskCount=rejected.messages.filter(m=>m.type==='disk').length;await assert.rejects(rejected.request('load',{disk:fatalDisk}),/Controlled session/);await assert.rejects(rejected.request('save'),/not available/);check('Unexpected post-validation session failure is fatal and cannot overwrite save',await rejected.read('BloomDiagnostics.fatal')&&rejected.messages.filter(m=>m.type==='disk').length===diskCount);
 const combatBaseline=process.env.BLOOM_COMBAT_BASELINE||`${__dirname}/fixtures/runtime-combat-baseline.html`;
 const combatParity=await require('./unit-update-parity.cjs').run({baseline:combatBaseline,target:file,disk:await a.request('snapshot'),reportPath:`${__dirname}/combat-parity-results.json`});
 check('Continuing campaign preserves baseline combat bytes and complete effects',combatParity.status==='PASS'&&combatParity.resumedFromCheckpoint,{combatParity});
 report.status='PASS';
})().catch(error=>{report.status='FAIL';report.error=error.stack;console.error(error.stack);process.exitCode=1}).finally(async()=>{for(const w of allWorkers)await w.close();fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks.length,report:output},null,2))});
