'use strict';
// Usage: node tests/shared-world.cjs [candidate.html] [--sdk=/path/to/rollback-netcode.js]
// The optional SDK override is local-only, bundled in memory; no pin/cache edits.
// One continuing 1 -> 2 -> 5 campaign against actual HTML engine/SDK.
// In-memory reliable byte links replace signaling/RTC. Fresh VM realm reconnect
// models identity resume, not an actual browser refresh or storage integration.
// Declared fixtures grant earned resources/armies and place durable encounters at
// settled tick boundaries. Normal movement, commands, combat, membership,
// snapshots, and catch-up all run the real engine/SDK. No production source patch.
const assert=require('node:assert/strict');
const {candidate,campaign}=require('./shared-harness.cjs');
const source=candidate(),world=campaign(source);
function pass(label,data){console.log('PASS '+label+(data?' '+JSON.stringify(data):''))}
const participant=(e,id)=>e.json(`(()=>{const p=WorldPlayers.get(${JSON.stringify(id)}),d=WorldPlayers.data(p);return{id:p.playerId,owner:p.accountOwner,hp:p.leader.hp,x:p.leader.x,y:p.leader.y,level:d.campaign.abilities.level,xp:d.campaign.abilities.xp,chosen:d.campaign.abilities.chosen,growth:d.campaign.growthCards.choices,minerals:d.minerals,deaths:d.deaths,dead:d.dead,lifecycle:p.lifecycle,army:rarityOwnedCount(p.accountOwner)}})()`);
async function admit(id){const e=world.add(id);await world.until(()=>world.live().every(x=>x.run('bloomSession.ready')&&x.run('bloomSession.players.length')===world.live().length));await world.settle();return e}
(async()=>{
 const a=world.add('a');await world.ticks(35);assert.equal(a.run('WorldPlayers.all().length'),1);pass('one human starts a ticking shared world',await world.settle());
 const b=await admit('b');assert.notEqual(participant(a,'a').owner,participant(a,'b').owner);assert(Math.hypot(participant(a,'a').x-participant(a,'b').x,participant(a,'a').y-participant(a,'b').y)>1500);pass('second human joins the same running world');
 const startA=participant(a,'a'),startB=participant(a,'b');world.controls.set(a,{x:.6,y:0,manual:true});world.controls.set(b,{x:0,y:.6,manual:true});await world.ticks(12);assert(participant(a,'a').x>startA.x+1);assert(participant(a,'b').y>startB.y+1);pass('distinct human inputs move their own leaders');
 world.controls.set(a,{x:0,y:0,manual:true});world.controls.set(b,{x:0,y:0,manual:true});
 await world.fixture(`for(const p of WorldPlayers.all()){const d=WorldPlayers.data(p);d.minerals=10000;const ab=d.campaign.abilities;ab.level=3;ab.xp=abilityThreshold(3);moaSyncLevelHP(p.leader);p.leader.hp=p.leader.maxHp;rarityAcquire(p.accountOwner,'archer',1,p.playerId==='a'?2:3);const q=ThemedTerrain.safePoint(p.leader.x+160,p.leader.y,20),t=spawn('shellbug','enemy',q.x,q.y,{camp:0,rarityGrade:1});t.hp=t.maxHp=1e7;t.stun=1e6;t.aggroAt=t.wanderAt=state.time+1e6;state.camps[0].remaining++;t.qaDurable=p.playerId;damage(p.leader,t,17,'ranged');launchAbilityShot(t,11,{owner:p.leader,speed:1,range:1800,homing:true})}`);
 world.command(a,'abilityDraft');world.command(b,'growthDraft');await world.ticks(5);
 assert(a.run("WorldPlayers.data(WorldPlayers.get('a')).campaign.abilities.draft!==null"));assert.equal(a.run("WorldPlayers.data(WorldPlayers.get('b')).campaign.growthCards.draft"),null);
 const ability=a.json("WorldPlayers.data(WorldPlayers.get('a')).campaign.abilities");world.command(a,'abilityChoice',{cardId:ability.draft.ids[0],offer:ability.chosen});world.command(b,'growthChoice',{cardId:'rhythm',offer:0});await world.ticks(5);
 assert.equal(participant(a,'a').chosen,1);assert.equal(participant(a,'b').chosen,0);assert.equal(participant(a,'b').growth,0);assert.equal(participant(a,'a').growth,0);assert.equal(participant(a,'b').minerals,10000);pass('ability choices are participant-owned; retired paid growth commands remain inert');
 const foreignUid=a.run("rarityAccount(WorldPlayers.get('b').accountOwner).active[0].uid");world.command(a,'rarityLock',{uid:foreignUid,locked:true});await world.ticks(4);assert.equal(a.run(`rarityRecord(${foreignUid}).record.locked`),false);world.command(b,'rarityLock',{uid:foreignUid,locked:true});await world.ticks(4);assert.equal(a.run(`rarityRecord(${foreignUid}).record.locked`),true);
 assert.throws(()=>a.run("BloomSimulation.encodeCommand({version:1,type:'auto',enabled:true,playerId:'b'})"),/Command fields/);pass('foreign inventory commands and forged player fields are rejected');
 // Let a real SDK checkpoint capture the explicit fixture before a bootstrap.
 await world.ticks(35);assert(a.run('projectiles.length>0'),'real combat has in-flight shots');const wounded=a.json("state.units.filter(u=>u.qaDurable).map(u=>({id:u.id,hp:u.hp,max:u.maxHp}))");assert(wounded.every(u=>u.hp<u.max));
 const time=a.run('state.time'),bBefore=participant(a,'b');a.run("paused=true;modalKind='ability'");world.controls.set(a,{x:0,y:0,manual:true,suspended:true});world.controls.set(b,{x:0,y:.5,manual:true});await world.ticks(10);assert(a.run('state.time')>time);assert(participant(a,'b').y>bBefore.y);for(const u of wounded)assert(a.run(`idMap.get(${u.id}).hp`)<=u.hp);pass('primary-player menu leaves world combat and other input running');a.run("paused=false;modalKind=''");world.controls.set(b,{x:0,y:0,manual:true});
 // Queue immediately before membership preparation, while combat is active.
 world.command(b,'permanentMode',{mode:'follow'});const c=await admit('c');assert.equal(c.run("WorldPlayers.data(WorldPlayers.get('b')).campaign.permanents.mode"),'follow');assert(c.run('projectiles.length>0'));for(const u of wounded)assert(c.run(`idMap.get(${u.id}).hp`)<=u.hp);pass('late join preserves pending command, active projectiles, and enemy wounds');
 const d=await admit('d'),e=await admit('e');assert.equal(a.run("WorldPlayers.all().filter(p=>p.lifecycle==='active').length"),5);assert.equal(a.run('new Set(WorldPlayers.all().map(p=>p.accountOwner)).size'),5);assert.equal(participant(a,'c').chosen,0);assert.equal(participant(a,'c').growth,0);assert.equal(participant(a,'c').army,0);pass('five humans share one canonical world with fresh independent progression',await world.settle());
 const five=[a,b,c,d,e],directions=[[.45,0],[0,.45],[-.45,0],[0,-.45],[.25,.25]],positions=five.map(x=>participant(a,x.id));for(let i=0;i<five.length;i++)world.controls.set(five[i],{x:directions[i][0],y:directions[i][1],manual:true});await world.ticks(8);for(let i=0;i<five.length;i++){const moved=participant(a,five[i].id);assert(Math.hypot(moved.x-positions[i].x,moved.y-positions[i].y)>1,`independent movement for ${five[i].id}`);const axes=a.json(`(()=>{const m=WorldPlayers.get('${five[i].id}').leader;return[m.moveX,m.moveY]})()`);assert(Math.abs(axes[0]-directions[i][0])<.001&&Math.abs(axes[1]-directions[i][1])<.001);world.controls.set(five[i],{x:0,y:0,manual:true})}pass('five different control streams remain attributed to their own leader');
 // Stopped-boundary combat fixture: exercise production PvP gates and rewards.
 await world.fixture(`const pa=WorldPlayers.get('a'),pb=WorldPlayers.get('b'),m=pa.leader;const q=ThemedTerrain.safePoint(m.x+70,m.y,moaBodyRadius(pb.leader));Object.assign(pb.leader,{x:q.x,y:q.y});resetMoaBody(pb.leader);spatialUnit(pb.leader,true);pb.leader.rollInvulnerableMs=0;const own=state.units.find(u=>u.playerId==='b');Object.assign(own,{x:pb.leader.x+20,y:pb.leader.y});spatialUnit(own,true);globalThis.qaCombat={before:pb.leader.hp,xp:WorldPlayers.data(pb).campaign.abilities.xp,otherXP:WorldPlayers.data(pa).campaign.abilities.xp};damage(own,pb.leader,9,'ranged');qaCombat.ownHP=pb.leader.hp;damage(m,pb.leader,9,'ranged');qaCombat.otherHP=pb.leader.hp;const t=spawn('swordsman','enemy',own.x+10,own.y,{camp:0,rarityGrade:0});t.hp=1;state.camps[0].remaining++;damage(own,t,1e5,'ranged');qaCombat.afterXP=WorldPlayers.data(pb).campaign.abilities.xp;qaCombat.afterOtherXP=WorldPlayers.data(pa).campaign.abilities.xp;`);
 const combat=a.json('qaCombat');assert.equal(combat.ownHP,combat.before);assert(combat.otherHP<combat.before);assert(combat.afterXP>combat.xp);assert.equal(combat.afterOtherXP,combat.otherXP);pass('PvP hostility and army kill credit use the attacker faction',combat);
 // Primary death/recovery must not restore/reset the shared combat graph.
 await world.fixture(`const pc=WorldPlayers.get('c'),target=spawn('shellbug','enemy',pc.leader.x+160,pc.leader.y,{camp:0,rarityGrade:1});target.hp=target.maxHp=1e7;target.stun=1e6;target.aggroAt=target.wanderAt=state.time+1e6;state.camps[0].remaining++;target.qaDurable='c';damage(pc.leader,target,17,'ranged');globalThis.qaForeignShot=launchAbilityShot(target,11,{owner:pc.leader,speed:1,range:1800,homing:true}).shotId;const p=WorldPlayers.get('a');globalThis.qaDeath={shots:projectiles.filter(s=>s.playerId!=='a').map(s=>s.shotId||s.u+':'+s.target),wounds:state.units.filter(u=>(u.qaDurable==='a'||u.qaDurable==='c')).map(u=>({id:u.id,hp:u.hp}))};PlayerLifecycle.defeat(p,WorldPlayers.get('b').leader);globalThis.qaAfterDeath={shots:projectiles.filter(s=>s.playerId!=='a').map(s=>s.shotId||s.u+':'+s.target),wounds:state.units.filter(u=>(u.qaDurable==='a'||u.qaDurable==='c')).map(u=>({id:u.id,hp:u.hp}))}`);
 assert.deepEqual(a.json('qaDeath'),a.json('qaAfterDeath'));assert(participant(a,'a').dead);const deathTime=a.run('state.time');await world.ticks(4);assert(a.run('state.time')>deathTime);world.command(a,'recover');await world.ticks(4);assert(!participant(a,'a').dead);for(const u of a.json('qaDeath.wounds'))assert(a.run(`idMap.get(${u.id}).hp`)<=u.hp);assert(a.run('projectiles.some(s=>s.shotId===qaForeignShot)'));pass('primary death and recovery preserve shared shots/wounds and world time');
 // Snapshot/load are pure and exactly preserve participant aliases and commands.
 await world.settle();for(const x of world.live()){const before=Buffer.from(x.run('bloomAdapter.save()'));x.c.qaRestore=Uint8Array.from(before);x.run('bloomAdapter.load(qaRestore)');assert.deepEqual(Buffer.from(x.run('bloomAdapter.save()')),before);assert(x.run("WorldPlayers.get('a').leader===state.mother&&WorldPlayers.get('b').data.mother===WorldPlayers.get('b').leader"))}pass('snapshot restore preserves exact shared graph bytes and actor identity aliases');
 await world.ticks(35);const bBeforeRefresh=participant(a,'b'),epoch=a.run('state.membershipEpoch');b.run('bloomSession.close()');const refreshed=world.add('b',{resumed:true});await world.until(()=>world.live().every(x=>x.run('bloomSession.ready')&&x.run('state.membershipEpoch')===epoch+1));await world.settle();const after=participant(refreshed,'b');assert.equal(after.owner,bBeforeRefresh.owner);assert.equal(after.chosen,bBeforeRefresh.chosen);assert.equal(after.growth,bBeforeRefresh.growth);assert.equal(after.army,bBeforeRefresh.army);assert.equal(after.minerals,bBeforeRefresh.minerals);assert.equal(a.run('bloomSession.players.length'),5);pass('fresh engine realm with same identity resumes existing progression and army');
 pass('recorded real adapter membership/input replay is byte-identical',world.replay(a));
 let left=false,leaveError;a.run('bloomSession.leave()').then(()=>left=true,error=>leaveError=error);await world.until(()=>left&&world.live().every(x=>x.run("bloomSession.ready&&bloomSession.players.length===4&&bloomSession.coordinatorId==='b'")));assert(!leaveError,leaveError?.message);await world.ticks(8);assert.equal(refreshed.run("WorldPlayers.get('a').lifecycle"),'left');assert.equal(refreshed.run("state.units.filter(u=>u.playerId==='a').length"),0);pass('coordinator departs gracefully while remaining shared world continues',await world.settle());
 // Full isolated partition: no fallback host or unilateral roster mutation.
 const remaining=world.live(),partitionEpoch=refreshed.run('state.membershipEpoch');for(let i=0;i<remaining.length;i++)for(let j=i+1;j<remaining.length;j++)world.net.disconnect(remaining[i].id,remaining[j].id);
 await world.until(()=>remaining.every(x=>x.run('!!bloomSession.failure')),{allowFailure:true,ms:500,limit:120});const stopped=remaining.map(x=>x.run('bloomTick')),stoppedState=remaining.map(x=>Buffer.from(x.run('bloomAdapter.save()')));for(let i=0;i<10;i++)await world.pulse({allowFailure:true,ms:500});assert.deepEqual(remaining.map(x=>x.run('bloomTick')),stopped);for(let i=0;i<remaining.length;i++)assert.deepEqual(Buffer.from(remaining[i].run('bloomAdapter.save()')),stoppedState[i],'fail-closed preserves every authoritative byte');assert(remaining.every(x=>x.run("bloomSession.coordinatorId==='b'")));assert(remaining.every(x=>x.run('state.membershipEpoch')===partitionEpoch));assert(remaining.every(x=>x.run("bloomSession.failure.type==='partition-failed'&&bloomSession.failure.policy==='fail-closed'")));pass('partition fails closed without advancing simulation or inventing membership',world.failures());
 pass('continuous shared-world campaign complete',{sha256:source.sha256,sdk:source.sdk,packets:world.net.delivered});
})().catch(error=>{console.error(error);console.error(JSON.stringify(world.failures()));process.exitCode=1}).finally(()=>world.close());
